version: '3.9'

services:
  app:
    build:
      context: .
    environment:
      - PORT=${PORT:-7991}
    ports:
      - "${PORT:-7991}:${PORT:-7991}"
    volumes:
      - .:/code
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
